// Workspace export/import as a portable `.opspack` archive.
// Defined in PRD §FM-PORTABILITY-01 / 02.
//
// Layout of the archive (zip):
//
//   manifest.json      // version, source workspace id, type, created, contents
//   workspace/         // mirror of `<workspacesRoot>/<wsId>/`
//     workspace.yaml
//     members/<id>.yaml
//     skills/...
//     profiles/...
//     philosophies/...
//     facts/...        // when includeFacts=true
//
// Secrets — API keys and AuthProfile cookie jars — are stripped before
// archiving. The importer rejects packs whose manifest version exceeds the
// host's supported version.

import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';
import 'package:archive/archive_io.dart';
import 'package:path/path.dart' as p;

class OpspackManifest {
  OpspackManifest({
    required this.formatVersion,
    required this.sourceWorkspaceId,
    required this.workspaceType,
    required this.createdAt,
    required this.includeFacts,
    required this.contents,
  });

  /// Bumped only when the layout changes incompatibly.
  static const int currentFormatVersion = 1;

  final int formatVersion;
  final String sourceWorkspaceId;
  final String workspaceType;
  final DateTime createdAt;
  final bool includeFacts;
  final List<String> contents;

  Map<String, Object?> toJson() => {
    'formatVersion': formatVersion,
    'sourceWorkspaceId': sourceWorkspaceId,
    'workspaceType': workspaceType,
    'createdAt': createdAt.toIso8601String(),
    'includeFacts': includeFacts,
    'contents': contents,
  };

  static OpspackManifest fromJson(Map<String, Object?> j) => OpspackManifest(
    formatVersion: (j['formatVersion'] as num).toInt(),
    sourceWorkspaceId: j['sourceWorkspaceId'] as String,
    workspaceType: j['workspaceType'] as String? ?? 'unknown',
    createdAt: DateTime.parse(j['createdAt'] as String),
    includeFacts: j['includeFacts'] as bool? ?? false,
    contents: (j['contents'] as List?)?.cast<String>() ?? const <String>[],
  );
}

/// Output of [Opspack.exportWorkspace] — the bytes ready to write to disk.
class OpspackBundle {
  OpspackBundle({required this.bytes, required this.manifest});
  final List<int> bytes;
  final OpspackManifest manifest;
}

/// Preview shown to the user before they confirm an import.
class OpspackPreview {
  OpspackPreview({
    required this.manifest,
    required this.fileCount,
    required this.bytes,
  });
  final OpspackManifest manifest;
  final int fileCount;
  final int bytes;
}

class Opspack {
  Opspack._();

  /// Build a `.opspack` for the workspace rooted at [workspaceDir].
  ///
  /// Files we never include even if present on disk:
  /// - `secrets.yaml`, `*.key`, `*.pem`, `auth_profile/*` (browser cookie jars)
  /// - any file inside an `auth/` or `secrets/` subtree
  ///
  /// `includeFacts` controls whether the in-workspace KV-backed FactGraph is
  /// included; off by default since facts can be regenerated by the host.
  static Future<OpspackBundle> exportWorkspace({
    required Directory workspaceDir,
    required String workspaceId,
    String workspaceType = 'unknown',
    bool includeFacts = false,
  }) async {
    if (!await workspaceDir.exists()) {
      throw StateError('Workspace dir not found: ${workspaceDir.path}');
    }

    final archive = Archive();
    final included = <String>[];

    await for (final entity in workspaceDir.list(
      recursive: true,
      followLinks: false,
    )) {
      if (entity is! File) continue;
      final rel = p.relative(entity.path, from: workspaceDir.path);
      if (_isSensitive(rel)) continue;
      if (!includeFacts && _isFacts(rel)) continue;
      final bytes = await entity.readAsBytes();
      archive.addFile(ArchiveFile('workspace/$rel', bytes.length, bytes));
      included.add(rel);
    }

    final manifest = OpspackManifest(
      formatVersion: OpspackManifest.currentFormatVersion,
      sourceWorkspaceId: workspaceId,
      workspaceType: workspaceType,
      createdAt: DateTime.now().toUtc(),
      includeFacts: includeFacts,
      contents: included,
    );
    final manifestBytes = utf8.encode(
      const JsonEncoder.withIndent('  ').convert(manifest.toJson()),
    );
    archive.addFile(
      ArchiveFile('manifest.json', manifestBytes.length, manifestBytes),
    );

    final encoded = ZipEncoder().encode(archive);
    if (encoded == null) {
      throw StateError('Failed to encode opspack archive');
    }
    return OpspackBundle(bytes: encoded, manifest: manifest);
  }

  /// Read a pack file's manifest + count without unpacking. Used by the
  /// import dialog to show a preview before the user confirms.
  static Future<OpspackPreview> previewFile(File file) async {
    final raw = await file.readAsBytes();
    return previewBytes(raw);
  }

  static OpspackPreview previewBytes(List<int> raw) {
    final archive = ZipDecoder().decodeBytes(raw);
    final manifestEntry = archive.findFile('manifest.json');
    if (manifestEntry == null) {
      throw StateError('Not a valid .opspack — manifest.json missing');
    }
    final manifest = OpspackManifest.fromJson(
      json.decode(utf8.decode(manifestEntry.content as List<int>))
          as Map<String, Object?>,
    );
    if (manifest.formatVersion > OpspackManifest.currentFormatVersion) {
      throw StateError(
        'Pack format ${manifest.formatVersion} newer than host '
        '${OpspackManifest.currentFormatVersion} — upgrade Ops to import.',
      );
    }
    final files = archive.where((f) => f.isFile).length;
    return OpspackPreview(
      manifest: manifest,
      fileCount: files,
      bytes: raw.length,
    );
  }

  /// Conflict policy used when [importWorkspace] meets a workspace whose
  /// id matches the manifest's [sourceWorkspaceId].
  static const conflictRename = 'rename';
  static const conflictSkip = 'skip';
  static const conflictOverwrite = 'overwrite';

  /// Unpack [packFile] into [workspacesRoot]. Returns the workspace id used
  /// (which may be a renamed variant on conflict).
  static Future<String> importWorkspace({
    required File packFile,
    required Directory workspacesRoot,
    String conflictPolicy = conflictRename,
    String? renamedTo,
  }) async {
    final raw = await packFile.readAsBytes();
    final archive = ZipDecoder().decodeBytes(raw);
    final manifestEntry = archive.findFile('manifest.json');
    if (manifestEntry == null) {
      throw StateError('Not a valid .opspack — manifest.json missing');
    }
    final manifest = OpspackManifest.fromJson(
      json.decode(utf8.decode(manifestEntry.content as List<int>))
          as Map<String, Object?>,
    );

    String targetId = renamedTo ?? manifest.sourceWorkspaceId;
    final targetDir = Directory(p.join(workspacesRoot.path, targetId));

    if (await targetDir.exists()) {
      switch (conflictPolicy) {
        case conflictSkip:
          return targetId;
        case conflictOverwrite:
          await targetDir.delete(recursive: true);
          break;
        case conflictRename:
        default:
          targetId = _suggestRenamed(
            workspacesRoot,
            manifest.sourceWorkspaceId,
          );
          break;
      }
    }
    final finalDir = Directory(p.join(workspacesRoot.path, targetId));
    await finalDir.create(recursive: true);

    for (final entry in archive) {
      if (!entry.isFile) continue;
      if (entry.name == 'manifest.json') continue;
      if (!entry.name.startsWith('workspace/')) continue;
      final rel = entry.name.substring('workspace/'.length);
      final out = File(p.join(finalDir.path, rel));
      await out.parent.create(recursive: true);
      await out.writeAsBytes(entry.content as List<int>);
    }
    return targetId;
  }

  static bool _isSensitive(String rel) {
    final lower = rel.toLowerCase();
    if (lower.endsWith('.key') || lower.endsWith('.pem')) return true;
    if (lower == 'secrets.yaml' || lower == 'secrets.json') return true;
    final segs = p.split(lower);
    if (segs.contains('secrets') || segs.contains('auth')) return true;
    if (segs.contains('auth_profile')) return true;
    return false;
  }

  static bool _isFacts(String rel) {
    final segs = p.split(rel);
    return segs.contains('facts') || segs.contains('factgraph');
  }

  static String _suggestRenamed(Directory root, String base) {
    var i = 2;
    while (true) {
      final cand = '$base-imported-$i';
      if (!Directory(p.join(root.path, cand)).existsSync()) return cand;
      i += 1;
    }
  }
}
