/// Host-level io capability — OS process execution + connection device
/// drivers (modbus / mqtt / http / scpi / … via mcp_io).
///
/// Exposes the fixed `io.*` surface + `io.connect_device` /
/// `io.disconnect_device` on the shared [HostToolRegistry], over one
/// host-owned [IoRuntime]. The wiring is the **vendored io_drivers recipe**
/// (`io_drivers/`, a committed copy of `brain_kernel/recipes/io_drivers` —
/// kept in-tree so the open-source clone stays hosted-clean; regenerated by
/// `debug/tool/sync_io_drivers_fork.sh`, never hand-edited). Studio and
/// AppPlayer consume the identical recipe so the same bundle drives devices
/// the same way (parity).
///
/// Two registration modes (spec `11-io-devices.md`):
///   - **boot** — `process` (host-owned, target-less) via the recipe's
///     [bootAdapters]; registered lazily on the first `io.*` call.
///   - **on-connect** — network drivers via [registerNetworkDrivers], built
///     at runtime through `io.connect_device`.
///
/// All execution / driver / sandbox / policy logic lives in the mcp_io
/// packages and the recipe; the host only wires the runtime, fills the
/// process options, and exposes the recipe's tool map (builtin = wiring only).
library;

import 'dart:convert' show jsonEncode;

import 'package:brain_kernel/brain_kernel.dart';
import 'package:mcp_io/mcp_io.dart';

import 'io_drivers/io_drivers.dart';

/// Capability namespace — exposed names are `io.<verb>`.
const String ioCapabilityId = 'io';

/// Register the io capability onto [registry] via the vendored io_drivers
/// recipe: the fixed `io.*` surface + `io.connect_device` /
/// `io.disconnect_device`, backed by one [IoRuntime] with the recipe's boot
/// adapters (process) and network connection drivers. Returns exposed names.
///
/// Synchronous like the other capability registrars (`buildServer` is sync):
/// tool metadata is static, so tools register immediately; the runtime +
/// device discovery boot **lazily** on the first `io.*` call.
///
/// Deny-by-default — process runs nothing until [executableAllowlist] /
/// [allowedRoots] are filled; [roles] opts actor roles into `process.*`
/// (`process.spawn` stays plan→commit); [allowShell] stays false unless the
/// host needs pipes/redirects. These flow into the recipe's [ProcessOptions]
/// so process config/policy is identical across hosts.
List<String> registerIoCapability({
  required HostToolRegistry registry,
  List<String> executableAllowlist = const <String>[],
  List<String> allowedRoots = const <String>[],
  List<String> roles = const <String>['manager', 'operator'],
  bool allowShell = false,
}) {
  final runtime = IoRuntime(
    policyPort: InMemoryIoPolicyPort(
      initialRules: recommendedPolicyRules(roles: roles),
    ),
    auditPort: InMemoryAuditPort(),
  );
  // Boot adapters (process on desktop) — from the recipe, not hand-built.
  final boot = bootAdapters(
    platform: DevicePlatform.desktop,
    process: ProcessOptions(
      executableAllowlist: executableAllowlist,
      allowedRoots: allowedRoots,
      allowShell: allowShell,
      roles: roles,
    ),
  );
  Future<void>? ready;
  Future<void> ensureReady() =>
      ready ??= () async {
        await runtime.initialize();
        for (final adapter in boot) {
          await runtime.registry.registerAdapter(adapter.manifest, adapter);
        }
        await runtime.registry.discover();
      }();

  // Connection drivers (network: modbus/mqtt/http/scpi) — recipe builders.
  final drivers = IoDriverRegistry();
  registerNetworkDrivers(drivers);

  // Host-agnostic tool map: fixed io.* (passthrough) + connect/disconnect.
  final toolMap = ioDeviceTools(
    runtime: runtime,
    registry: drivers,
    platform: DevicePlatform.desktop,
  );

  // Metadata: io.* from IoTools.tools; connect/disconnect defined locally.
  final ioTools = IoTools(runtime: runtime);

  final exposed = <String>[];
  toolMap.forEach((name, handler) {
    final verb = name.startsWith('io.') ? name.substring(3) : name;
    exposed.add(
      registry.registerExposed(
        bundleId: ioCapabilityId,
        rawName: verb,
        // §6 destructive — device commands / committed plans actuate the
        // physical or process world (incl. shell runs like git push) and
        // can't be undone; gated through the host confirm callback. Reads /
        // describes / job queries stay un-gated.
        destructive: verb == 'execute' || verb == 'commit_execute',
        description: _descFor(name, ioTools),
        inputSchema: _schemaFor(name, ioTools),
        handler: (args) async {
          try {
            await ensureReady();
            final out = await handler(args);
            final m = out is Map ? out : const <String, dynamic>{};
            if (m['isError'] == true) {
              return _result(<String, dynamic>{
                'ok': false,
                'code': 'io.error',
                'error': m['errorMessage'] ?? 'io operation failed',
              }, isError: true);
            }
            return _result(<String, dynamic>{
              'ok': true,
              'content': m['content'],
            }, isError: false);
          } catch (e) {
            return _result(<String, dynamic>{
              'ok': false,
              'code': 'io.error',
              'error': e.toString(),
            }, isError: true);
          }
        },
      ),
    );
  });
  return exposed;
}

String _descFor(String name, IoTools ioTools) {
  for (final t in ioTools.tools) {
    if (t.name == name) return t.description ?? '';
  }
  switch (name) {
    case 'io.connect_device':
      return 'Provision (connect) a connection driver instance at runtime '
          '({type, id, params}). Platform-gated by the host.';
    case 'io.disconnect_device':
      return 'Release a runtime-provisioned device by id.';
    default:
      return '';
  }
}

Map<String, dynamic> _schemaFor(String name, IoTools ioTools) {
  for (final t in ioTools.tools) {
    if (t.name == name) {
      return t.inputSchema == null
          ? const <String, dynamic>{'type': 'object'}
          : Map<String, dynamic>.from(t.inputSchema!);
    }
  }
  switch (name) {
    case 'io.connect_device':
      return const <String, dynamic>{
        'type': 'object',
        'properties': <String, dynamic>{
          'type': <String, dynamic>{'type': 'string'},
          'id': <String, dynamic>{'type': 'string'},
          'params': <String, dynamic>{'type': 'object'},
        },
        'required': <String>['type', 'id'],
      };
    case 'io.disconnect_device':
      return const <String, dynamic>{
        'type': 'object',
        'properties': <String, dynamic>{
          'id': <String, dynamic>{'type': 'string'},
        },
        'required': <String>['id'],
      };
    default:
      return const <String, dynamic>{'type': 'object'};
  }
}

KernelToolResult _result(Object? value, {required bool isError}) {
  return KernelToolResult(
    content: <KernelContent>[KernelTextContent(text: jsonEncode(value))],
    isError: isError,
  );
}
