/// Registers the notices of what the app ships beyond Dart packages with the
/// platform's [OpenSourceLicenses] (appplayer_core), so the one license page
/// (Settings → About) lists everything:
///
///   * `apple.json` — native code on macOS: Swift packages, CocoaPods and
///     binary artifacts (FFmpeg and its components, PDFium and its
///     components). Written by appplayer_core's Apple generator per app; a
///     tier that links more (Pro) supplies its own list through
///     [appleLicenseList].
///   * `desktop.json` — what no platform generator lists: QuickJS and
///     libserialport (Windows / Linux builds) and the bundled font.
///
/// Both use the platform format `[{"packages": [..], "license": ".."}]` and
/// are regenerated by the monorepo tool `tool/sync_third_party_licenses.py`.
library;

import 'dart:io' show Platform;

import 'package:appplayer_core/appplayer_core.dart' show OpenSourceLicenses;
import 'package:flutter/foundation.dart' show FlutterError;
import 'package:flutter/services.dart';

/// Where this build's macOS notice list lives. The open studio ships its own;
/// a tier that links more native code sets its list before boot.
String appleLicenseList = 'assets/licenses/apple.json';

const String kDesktopLicenseList = 'assets/licenses/desktop.json';

// Built as the app (standard) the assets sit at their bare key; under the Pro
// tier the open studio's assets sit under `packages/appplayer_studio/…` —
// same idiom as the discovery trust anchor and the project seeds.
const String _packageAssetPrefix = 'packages/appplayer_studio';

/// Registers this build's notice lists. Idempotent (per list, inside
/// [OpenSourceLicenses]). [bundle] is injectable for tests; [macOS]
/// defaults to the running platform.
void registerThirdPartyLicenses({AssetBundle? bundle, bool? macOS}) {
  final assets = _PackageFallbackBundle(bundle ?? rootBundle);
  OpenSourceLicenses.registerBundled(kDesktopLicenseList, bundle: assets);
  if (macOS ?? Platform.isMacOS) {
    OpenSourceLicenses.registerBundled(appleLicenseList, bundle: assets);
  }
}

/// Reads a key as given and, when the app bundles it under the open studio's
/// package prefix instead, from there.
class _PackageFallbackBundle extends CachingAssetBundle {
  _PackageFallbackBundle(this._inner);

  final AssetBundle _inner;

  @override
  Future<ByteData> load(String key) async {
    try {
      return await _inner.load(key);
    } on FlutterError {
      return _inner.load('$_packageAssetPrefix/$key');
    }
  }
}
