import 'dart:convert';
import 'dart:io';

import 'package:brain_kernel/brain_kernel.dart' show McpBundle;
import 'package:path/path.dart' as p;

import '../types/builder_exceptions.dart';
import 'pattern_enforcer.dart';

/// Converts the canonical UI section into the chip's own display code
/// (LVGL, Qt, or other) plus a host simulator build script.
abstract interface class SelfUiConverter {
  Future<ConvertResult> run({
    required McpBundle canonical,
    required SelfUiFramework framework,
    required String outDir,
  });
}

enum SelfUiFramework { lvgl, qt, none }

/// Default implementation. Emits a minimal LVGL or Qt skeleton plus a host
/// simulator build script.
class SelfUiConverterImpl implements SelfUiConverter {
  SelfUiConverterImpl({PatternEnforcer? enforcer})
    : _enforcer = enforcer ?? const PatternEnforcerImpl();

  final PatternEnforcer _enforcer;

  @override
  Future<ConvertResult> run({
    required McpBundle canonical,
    required SelfUiFramework framework,
    required String outDir,
  }) async {
    if (framework == SelfUiFramework.none) {
      throw UnimplementedError('framework=none has no output');
    }
    final violations = _enforcer.check(
      canonical,
      ConvertTarget(family: 'selfui', subKind: framework.name),
    );
    if (violations.isNotEmpty) {
      throw PatternException(violations);
    }
    final dir = Directory(outDir);
    await dir.create(recursive: true);
    final written = <String>[];
    final canonicalJson = jsonEncode(canonical.toJson());
    final canonicalHash =
        'sha256:${canonicalJson.hashCode.toUnsigned(63).toRadixString(16)}';

    if (framework == SelfUiFramework.lvgl) {
      final main = File(p.join(outDir, 'src', 'ui_main.c'));
      await main.parent.create(recursive: true);
      await main.writeAsString(_lvglMainSource);
      written.add(main.path);

      final sim = File(p.join(outDir, 'sim_build.sh'));
      await sim.writeAsString('#!/bin/sh\n# LVGL host simulator build\n');
      written.add(sim.path);
    } else if (framework == SelfUiFramework.qt) {
      final main = File(p.join(outDir, 'qml', 'Main.qml'));
      await main.parent.create(recursive: true);
      await main.writeAsString(_qtMainSource);
      written.add(main.path);

      final sim = File(p.join(outDir, 'sim_build.sh'));
      await sim.writeAsString('#!/bin/sh\n# Qt host simulator build\n');
      written.add(sim.path);
    }

    final manifest = File(p.join(outDir, 'convert.json'));
    await manifest.writeAsString(
      jsonEncode(<String, dynamic>{
        'target': 'selfui',
        'framework': framework.name,
        'generated_at': DateTime.now().toUtc().toIso8601String(),
        'canonical_hash': canonicalHash,
      }),
    );
    written.add(manifest.path);

    return ConvertResult(
      outDir: outDir,
      canonicalHash: canonicalHash,
      writtenFiles: written,
    );
  }

  static const String _lvglMainSource = '''
/* Generated by vibe_app_builder (self-ui LVGL). */
#include "lvgl.h"
void ui_main_init(void) {
  /* TODO: build LVGL tree from canonical UI sections. */
}
''';

  static const String _qtMainSource = '''
// Generated by vibe_app_builder (self-ui Qt).
import QtQuick
import QtQuick.Controls
ApplicationWindow {
    visible: true
    width: 320
    height: 240
}
''';
}
