/// vibe_studio_runtime — vendored namespace fork of
/// flutter_mcp_ui_runtime. Same source, distinct Dart package URI so
/// classes (NavigationService / WidgetCache / ThemeManager / ...)
/// become separate types with separate static singletons. Enables a
/// vibe_studio MCPUIRuntime instance to coexist with the host's
/// flutter_mcp_ui_runtime instance without global-state collision.
///
/// The source under `src/runtime/` is a committed COPY (not a symlink),
/// generated from the monorepo's flutter_mcp_ui_runtime by a monorepo
/// dev tool (`debug/tool/sync_runtime_fork.sh`, outside this repo) — so
/// an open-source clone of `standard` builds standalone. Never hand-edit
/// `src/runtime/`; it is regenerated by that tool.
library;

export 'src/runtime/flutter_mcp_ui_runtime.dart';
