// VENDORED from `os/core/brain_kernel/recipes/composition_host/lib/composition_host.dart`
// (recipe 0.0.1). Generated by debug/tool/sync_composition_host_fork.sh.
//
// A copy, not a dependency: the recipe is `publish_to: none` and this is the
// OPEN tree, which must build from a standalone clone where a path outside the
// repo does not resolve. Studio Pro depends on the recipe by path instead.
//
// Fix at the recipe and re-run the sync script — never edit only this copy, or
// the reference another host follows stops describing what the platform does.
// Everything below this header is byte-identical to the recipe.
/// composition_host — how a host claims the MCP UI DSL v1.4 Composition
/// Profile, so one bundle can render, drive and track several MCP servers as
/// one product.
///
/// The runtime asks a host for three things and all three ride the kernel's
/// outbound `mcp.*` surface, which platform spec `06-tool-registry.md` already
/// declares as the default path for an app driving its own server connections.
/// Composition therefore needs no new transport, no second connection registry
/// and no manifest field — only these hooks:
///
/// ```dart
/// final hooks = buildCompositionHooks(
///   call: (tool, args) => dispatcher.callInProcess(tool, args),
///   clientHost: () => kernel.clientHost,
///   openOrigin: (id) => myHost.openDevice(id),
/// );
/// runtime
///   ..registerDefinitionResolver(hooks.resolveDefinition)
///   ..registerOriginToolCaller(hooks.callTool)
///   ..registerOriginResourceWatcher(hooks.watchResource);
/// ```
///
/// Registering the resolver is what CLAIMS the profile: without it a `view`
/// fails closed and renders its fallback rather than resolving a foreign `$ref`
/// against the host's own server. Registering only the resolver ships a screen
/// that renders and does nothing — hence one object carrying all three.
library composition_host;

export 'src/composition_host.dart'
    show
        CompositionHooks,
        KernelToolCall,
        OpenOrigin,
        ReadOwnDefinition,
        buildCompositionHooks,
        definitionFromReadResource,
        unwrapResourceContents;
