import 'dart:convert';
import 'dart:io';

import 'package:mcp_bundle/mcp_bundle.dart' show McpBundle;
import 'package:path/path.dart' as p;

import '../core/types.dart';
import 'pattern_enforcer.dart';

/// Converts the canonical bundle into an embedded C/C++ MCP server. The
/// `native` mode transpiles UI/Skill into code (no filesystem on the chip).
/// The `withBundle` mode lays out the `.mbd/` for chips with FS plus a
/// generic loader.
abstract interface class EmbedConverter {
  Future<ConvertResult> run({
    required McpBundle canonical,
    required EmbedMode mode,
    required String board,
    required String outDir,
  });
}

enum EmbedMode { native, withBundle }

class EmbedException implements Exception {
  EmbedException(this.message);
  final String message;
  @override
  String toString() => 'EmbedException: $message';
}

/// Default implementation. Emits a placeholder native server skeleton + a
/// build template for the requested board family.
class EmbedConverterImpl implements EmbedConverter {
  EmbedConverterImpl({PatternEnforcer? enforcer})
    : _enforcer = enforcer ?? const PatternEnforcerImpl();

  final PatternEnforcer _enforcer;

  static const Set<String> _supportedBoards = <String>{
    'esp32',
    'stm32f4',
    'rp2040',
    'linux-host',
  };

  @override
  Future<ConvertResult> run({
    required McpBundle canonical,
    required EmbedMode mode,
    required String board,
    required String outDir,
  }) async {
    if (!_supportedBoards.contains(board)) {
      throw EmbedException(
        'unsupported board "$board"; supported: ${_supportedBoards.join(", ")}',
      );
    }
    final violations = _enforcer.check(
      canonical,
      ConvertTarget(family: 'embed_c', subKind: mode.name),
    );
    if (violations.isNotEmpty) {
      throw PatternException(violations);
    }
    final dir = Directory(outDir);
    await dir.create(recursive: true);
    final written = <String>[];
    final canonicalJson = jsonEncode(canonical.toJson());
    final canonicalHash =
        'sha256:${canonicalJson.hashCode.toUnsigned(63).toRadixString(16)}';

    final serverFile = File(p.join(outDir, 'src', 'server.c'));
    await serverFile.parent.create(recursive: true);
    await serverFile.writeAsString(
      mode == EmbedMode.native ? _nativeServerSource : _bundleServerSource,
    );
    written.add(serverFile.path);

    final cmake = File(p.join(outDir, 'CMakeLists.txt'));
    await cmake.writeAsString(_cmakeFor(board));
    written.add(cmake.path);

    if (mode == EmbedMode.withBundle) {
      final dataDir = Directory(p.join(outDir, 'data'));
      await dataDir.create(recursive: true);
      final dump = File(p.join(dataDir.path, 'manifest.json'));
      await dump.writeAsString(canonicalJson);
      written.add(dump.path);
    }

    final manifest = File(p.join(outDir, 'convert.json'));
    await manifest.writeAsString(
      jsonEncode(<String, dynamic>{
        'target': 'embed_c',
        'mode': mode.name,
        'board': board,
        'generated_at': DateTime.now().toUtc().toIso8601String(),
        'canonical_hash': canonicalHash,
      }),
    );
    written.add(manifest.path);

    return ConvertResult(
      outDir: outDir,
      canonicalHash: canonicalHash,
      writtenFiles: written,
    );
  }

  static const String _nativeServerSource = '''
/* Generated by app_builder_vibe (embed native).
   Emits MCP UI DSL via in-code dsl_node()/dsl_prop() macros. */
#include <stdio.h>
int main(void) { return 0; }
''';

  static const String _bundleServerSource = '''
/* Generated by app_builder_vibe (embed with bundle).
   Loads ./data/manifest.json from a chip-side filesystem. */
#include <stdio.h>
int main(void) { return 0; }
''';

  static String _cmakeFor(String board) {
    return '''
# Generated by app_builder_vibe — board=$board
cmake_minimum_required(VERSION 3.16)
project(vibe_embed C)
add_executable(server src/server.c)
''';
  }
}
