// Workspace export/import page — `.opspack` round-trip surface.
// PRD §FM-PORTABILITY.

import 'dart:io';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;

import '../../portability/html_report.dart';
import '../../portability/opspack.dart';
import '../../state/providers.dart';
import '../../theme/tokens.dart';

class PortabilityPage extends ConsumerStatefulWidget {
  const PortabilityPage({super.key});

  @override
  ConsumerState<PortabilityPage> createState() => _PortabilityPageState();
}

class _PortabilityPageState extends ConsumerState<PortabilityPage> {
  String? _statusOk;
  String? _statusErr;
  bool _includeFacts = false;

  @override
  Widget build(BuildContext context) {
    final cfg = ref.watch(opsConfigProvider);
    final wsId = ref.watch(activeWorkspaceIdProvider);
    return Padding(
      padding: const EdgeInsets.all(16),
      child: ListView(
        children: [
          Text(
            'Workspace portability',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const SizedBox(height: 8),
          Text(
            'Export the active workspace as a `.opspack` archive to share it '
            'or move it to another machine. API keys and AuthProfile sessions '
            'are stripped automatically.',
            style: TextStyle(color: OpsColors.text2),
          ),
          const SizedBox(height: 16),
          _Card(
            title: 'Export — ${wsId ?? "no active workspace"}',
            children: [
              CheckboxListTile(
                dense: true,
                contentPadding: EdgeInsets.zero,
                title: const Text('Include FactGraph entries'),
                subtitle: const Text(
                  'Off by default — facts can be regenerated by the host.',
                ),
                value: _includeFacts,
                onChanged:
                    (v) => setState(() => _includeFacts = v ?? _includeFacts),
              ),
              const SizedBox(height: 8),
              FilledButton.icon(
                icon: const Icon(Icons.archive_outlined, size: 16),
                label: const Text('Export .opspack'),
                onPressed:
                    wsId == null
                        ? null
                        : () => _export(context, cfg.workspacesRoot, wsId),
              ),
            ],
          ),
          const SizedBox(height: 16),
          _Card(
            title: 'Import',
            children: [
              Text(
                'Importing creates a new workspace under the configured '
                'workspaces root. Existing workspaces are never overwritten — '
                'a unique id is auto-suggested on conflict.',
                style: TextStyle(color: OpsColors.text2),
              ),
              const SizedBox(height: 12),
              FilledButton.icon(
                icon: const Icon(Icons.unarchive_outlined, size: 16),
                label: const Text('Import .opspack'),
                onPressed: () => _import(context, cfg.workspacesRoot),
              ),
            ],
          ),
          const SizedBox(height: 16),
          _Card(
            title: 'Share — HTML report',
            children: [
              Text(
                'Render the workspace as a self-contained `.html` file you '
                'can open in any browser, attach to email, or host as a '
                'static page. No backend involved — the cloud-free '
                'alternative to embed share.',
                style: TextStyle(color: OpsColors.text2),
              ),
              const SizedBox(height: 12),
              FilledButton.icon(
                icon: const Icon(Icons.description_outlined, size: 16),
                label: const Text('Generate .html report'),
                onPressed:
                    wsId == null ? null : () => _exportHtml(context, wsId),
              ),
            ],
          ),
          const SizedBox(height: 16),
          if (_statusOk != null)
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: OpsColors.success.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(6),
                border: Border.all(
                  color: OpsColors.success.withValues(alpha: 0.3),
                ),
              ),
              child: Text(
                _statusOk!,
                style: TextStyle(color: OpsColors.success),
              ),
            ),
          if (_statusErr != null)
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: OpsColors.danger.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(6),
                border: Border.all(
                  color: OpsColors.danger.withValues(alpha: 0.3),
                ),
              ),
              child: Text(
                _statusErr!,
                style: TextStyle(color: OpsColors.danger),
              ),
            ),
        ],
      ),
    );
  }

  Future<void> _export(
    BuildContext context,
    String workspacesRoot,
    String wsId,
  ) async {
    setState(() {
      _statusOk = null;
      _statusErr = null;
    });
    try {
      final dir = Directory(p.join(workspacesRoot, wsId));
      final pack = await Opspack.exportWorkspace(
        workspaceDir: dir,
        workspaceId: wsId,
        includeFacts: _includeFacts,
      );
      final saveLocation = await getSaveLocation(
        suggestedName: '$wsId.opspack',
        acceptedTypeGroups: const [
          XTypeGroup(label: 'opspack', extensions: ['opspack', 'zip']),
        ],
      );
      if (saveLocation == null) return;
      await File(saveLocation.path).writeAsBytes(pack.bytes);
      if (!mounted) return;
      setState(
        () =>
            _statusOk =
                'Exported $wsId · ${pack.manifest.contents.length} files → ${saveLocation.path}',
      );
    } catch (e) {
      setState(() => _statusErr = 'Export failed: $e');
    }
  }

  Future<void> _exportHtml(BuildContext context, String wsId) async {
    setState(() {
      _statusOk = null;
      _statusErr = null;
    });
    try {
      final cfg = ref.read(opsConfigProvider);
      final init = ref.read(knowledgeInitProvider);
      final obs = ref.read(observabilityProvider);
      final saveLocation = await getSaveLocation(
        suggestedName: '${wsId.replaceAll("/", "_")}-report.html',
        acceptedTypeGroups: const [
          XTypeGroup(label: 'html', extensions: ['html']),
        ],
      );
      if (saveLocation == null) return;
      final result = await HtmlReport.build(
        init: init,
        config: cfg,
        workspaceId: wsId,
        outputPath: saveLocation.path,
        observability: obs,
      );
      if (!mounted) return;
      setState(
        () =>
            _statusOk =
                'Wrote ${result.bytes} bytes to ${result.path} — open in any browser.',
      );
    } catch (e) {
      setState(() => _statusErr = 'HTML report failed: $e');
    }
  }

  Future<void> _import(BuildContext context, String workspacesRoot) async {
    setState(() {
      _statusOk = null;
      _statusErr = null;
    });
    try {
      final picked = await openFile(
        acceptedTypeGroups: const [
          XTypeGroup(label: 'opspack', extensions: ['opspack', 'zip']),
        ],
      );
      if (picked == null) return;
      final preview = await Opspack.previewFile(File(picked.path));
      if (!context.mounted) return;
      final policy = await showDialog<String>(
        context: context,
        builder:
            (ctx) => AlertDialog(
              title: Text('Import "${preview.manifest.sourceWorkspaceId}"?'),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Files: ${preview.fileCount} · ${(preview.bytes / 1024).toStringAsFixed(1)} KB',
                  ),
                  Text('Type: ${preview.manifest.workspaceType}'),
                  Text('Created: ${preview.manifest.createdAt.toLocal()}'),
                  Text(
                    'Includes FactGraph: ${preview.manifest.includeFacts ? "yes" : "no"}',
                  ),
                  const SizedBox(height: 12),
                  Text(
                    'If a workspace named "${preview.manifest.sourceWorkspaceId}" already exists, choose a strategy:',
                  ),
                ],
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(ctx),
                  child: const Text('Cancel'),
                ),
                TextButton(
                  onPressed: () => Navigator.pop(ctx, Opspack.conflictRename),
                  child: const Text('Rename'),
                ),
                TextButton(
                  onPressed: () => Navigator.pop(ctx, Opspack.conflictSkip),
                  child: const Text('Skip'),
                ),
                FilledButton(
                  onPressed:
                      () => Navigator.pop(ctx, Opspack.conflictOverwrite),
                  child: const Text('Overwrite'),
                ),
              ],
            ),
      );
      if (policy == null) return;
      final id = await Opspack.importWorkspace(
        packFile: File(picked.path),
        workspacesRoot: Directory(workspacesRoot),
        conflictPolicy: policy,
      );
      if (!mounted) return;
      setState(
        () =>
            _statusOk =
                'Imported as "$id" — restart the app or switch workspace to load it.',
      );
    } catch (e) {
      setState(() => _statusErr = 'Import failed: $e');
    }
  }
}

class _Card extends StatelessWidget {
  const _Card({required this.title, required this.children});
  final String title;
  final List<Widget> children;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: OpsColors.surface,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: OpsColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              fontFamily: OpsType.sans,
              fontSize: 13,
              fontWeight: OpsType.semibold,
            ),
          ),
          const SizedBox(height: 8),
          ...children,
        ],
      ),
    );
  }
}
